package app.mediatracker.seed;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

import app.mediatracker.feature.library.model.UserLibraryEntry;
import app.mediatracker.feature.library.model.LibraryEntryStatus;

@Component
public class DemoMediaData {

    public List<UserLibraryEntry> createDemoMediaData() {
        List<UserLibraryEntry> mediaTestData = new ArrayList<>();

        UserLibraryEntry entry = new UserLibraryEntry();
        entry.setMediaType("anime");
        entry.setExternalId("an1");
        entry.setTitle("Attack on Titan");
        entry.setImageUrl("https://cdn.myanimelist.net/images/anime/10/47347.jpg");
        entry.setSourceUrl("https://anilist.co/anime/16498");
        entry.setAuthor("Hajime Isayama");
        entry.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta = new java.util.HashMap<>();
        meta.put("episodesWatched", 25);
        entry.setMeta(meta);
        entry.setRating(9);
        entry.setNotes("Spannend bis zum Schluss!");
        entry.setCreatedAt(java.time.Instant.parse("2024-01-01T10:00:00Z"));
        entry.setUpdatedAt(java.time.Instant.parse("2024-01-10T10:00:00Z"));
        mediaTestData.add(entry);

        UserLibraryEntry entry2 = new UserLibraryEntry();
        entry2.setMediaType("manga");
        entry2.setExternalId("mn1");
        entry2.setTitle("One Piece");
        entry2.setImageUrl("https://cdn.myanimelist.net/images/manga/3/55539.jpg");
        entry2.setSourceUrl("https://myanimelist.net/manga/13/One_Piece");
        entry2.setAuthor("Eiichiro Oda");
        entry2.setStatus(LibraryEntryStatus.IN_PROGRESS);
        java.util.Map<String, Object> meta2 = new java.util.HashMap<>();
        meta2.put("chaptersRead", 1050);
        entry2.setMeta(meta2);
        entry2.setRating(10);
        entry2.setNotes("Lange Reise, immer spannend.");
        entry2.setCreatedAt(java.time.Instant.parse("2023-05-01T12:00:00Z"));
        entry2.setUpdatedAt(java.time.Instant.parse("2024-01-15T09:00:00Z"));
        mediaTestData.add(entry2);

        UserLibraryEntry entry3 = new UserLibraryEntry();
        entry3.setMediaType("movie");
        entry3.setExternalId("mv1");
        entry3.setTitle("Inception");
        entry3.setImageUrl("https://media.themoviedb.org/t/p/w440_and_h660_face/t5WUY5ZSxwVIVExaMZmmIj88BKA.jpg");
        entry3.setSourceUrl("https://www.imdb.com/title/tt1375666/");
        entry3.setAuthor("Christopher Nolan");
        entry3.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta3 = new java.util.HashMap<>();
        meta3.put("timesWatched", 3);
        entry3.setMeta(meta3);
        entry3.setRating(8);
        entry3.setNotes("Mind-bending plot.");
        entry3.setCreatedAt(java.time.Instant.parse("2022-11-20T18:30:00Z"));
        entry3.setUpdatedAt(java.time.Instant.parse("2023-12-01T20:00:00Z"));
        mediaTestData.add(entry3);

        UserLibraryEntry entry4 = new UserLibraryEntry();
        entry4.setMediaType("book");
        entry4.setExternalId("bk1");
        entry4.setTitle("1984");
        entry4.setImageUrl("https://covers.openlibrary.org/b/id/7222246-L.jpg");
        entry4.setSourceUrl("https://openlibrary.org/works/OL7343625W/1984");
        entry4.setAuthor("George Orwell");
        entry4.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta4 = new java.util.HashMap<>();
        meta4.put("pagesRead", 328);
        entry4.setMeta(meta4);
        entry4.setRating(10);
        entry4.setNotes("Klassiker, sehr eindrucksvoll.");
        entry4.setCreatedAt(java.time.Instant.parse("2021-03-10T14:00:00Z"));
        entry4.setUpdatedAt(java.time.Instant.parse("2021-03-20T14:00:00Z"));
        mediaTestData.add(entry4);

        UserLibraryEntry entry5 = new UserLibraryEntry();
        entry5.setMediaType("game");
        entry5.setExternalId("gm1");
        entry5.setTitle("The Legend of Zelda: Breath of the Wild");
        entry5.setImageUrl("https://cdn.cloudflare.steamstatic.com/steam/apps/729040/header.jpg");
        entry5.setSourceUrl("https://www.zelda.com/breath-of-the-wild/");
        entry5.setAuthor("Nintendo");
        entry5.setStatus(LibraryEntryStatus.IN_PROGRESS);
        java.util.Map<String, Object> meta5 = new java.util.HashMap<>();
        meta5.put("hoursPlayed", 120);
        entry5.setMeta(meta5);
        entry5.setRating(10);
        entry5.setNotes("Open world at its best.");
        entry5.setCreatedAt(java.time.Instant.parse("2022-07-01T10:00:00Z"));
        entry5.setUpdatedAt(java.time.Instant.parse("2022-12-01T10:00:00Z"));
        mediaTestData.add(entry5);

        UserLibraryEntry entry6 = new UserLibraryEntry();
        entry6.setMediaType("anime");
        entry6.setExternalId("an2");
        entry6.setTitle("Fullmetal Alchemist: Brotherhood");
        entry6.setImageUrl("https://cdn.myanimelist.net/images/anime/1223/96541.jpg");
        entry6.setSourceUrl("https://anilist.co/anime/5114");
        entry6.setAuthor("Hiromu Arakawa");
        entry6.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta6 = new java.util.HashMap<>();
        meta6.put("episodesWatched", 64);
        entry6.setMeta(meta6);
        entry6.setRating(10);
        entry6.setNotes("Perfekte Story.");
        entry6.setCreatedAt(java.time.Instant.parse("2022-01-01T10:00:00Z"));
        entry6.setUpdatedAt(java.time.Instant.parse("2022-01-10T10:00:00Z"));
        mediaTestData.add(entry6);

        UserLibraryEntry entry7 = new UserLibraryEntry();
        entry7.setMediaType("manga");
        entry7.setExternalId("mn2");
        entry7.setTitle("Death Note");
        entry7.setImageUrl("https://cdn.myanimelist.net/images/anime/1079/138100.jpg");
        entry7.setSourceUrl("https://myanimelist.net/manga/7/Death_Note");
        entry7.setAuthor("Tsugumi Ohba");
        entry7.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta7 = new java.util.HashMap<>();
        meta7.put("chaptersRead", 108);
        entry7.setMeta(meta7);
        entry7.setRating(9);
        entry7.setNotes("Sehr spannend.");
        entry7.setCreatedAt(java.time.Instant.parse("2020-05-01T12:00:00Z"));
        entry7.setUpdatedAt(java.time.Instant.parse("2020-06-01T09:00:00Z"));
        mediaTestData.add(entry7);

        UserLibraryEntry entry8 = new UserLibraryEntry();
        entry8.setMediaType("movie");
        entry8.setExternalId("mv2");
        entry8.setTitle("The Matrix");
        entry8.setImageUrl("https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg");
        entry8.setSourceUrl("https://www.imdb.com/title/tt0133093/");
        entry8.setAuthor("The Wachowskis");
        entry8.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta8 = new java.util.HashMap<>();
        meta8.put("timesWatched", 5);
        entry8.setMeta(meta8);
        entry8.setRating(9);
        entry8.setNotes("Revolutionary sci-fi.");
        entry8.setCreatedAt(java.time.Instant.parse("2019-11-20T18:30:00Z"));
        entry8.setUpdatedAt(java.time.Instant.parse("2020-12-01T20:00:00Z"));
        mediaTestData.add(entry8);

        UserLibraryEntry entry9 = new UserLibraryEntry();
        entry9.setMediaType("book");
        entry9.setExternalId("bk2");
        entry9.setTitle("The Hobbit");
        entry9.setImageUrl("https://covers.openlibrary.org/b/id/6979861-L.jpg");
        entry9.setSourceUrl("https://openlibrary.org/works/OL262758W/The_Hobbit");
        entry9.setAuthor("J.R.R. Tolkien");
        entry9.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta9 = new java.util.HashMap<>();
        meta9.put("pagesRead", 310);
        entry9.setMeta(meta9);
        entry9.setRating(8);
        entry9.setNotes("Abenteuer pur.");
        entry9.setCreatedAt(java.time.Instant.parse("2018-03-10T14:00:00Z"));
        entry9.setUpdatedAt(java.time.Instant.parse("2018-03-20T14:00:00Z"));
        mediaTestData.add(entry9);

        UserLibraryEntry entry10 = new UserLibraryEntry();
        entry10.setMediaType("game");
        entry10.setExternalId("gm2");
        entry10.setTitle("The Witcher 3: Wild Hunt");
        entry10.setImageUrl("https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg");
        entry10.setSourceUrl("https://thewitcher.com/en/witcher3");
        entry10.setAuthor("CD Projekt Red");
        entry10.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta10 = new java.util.HashMap<>();
        meta10.put("hoursPlayed", 200);
        entry10.setMeta(meta10);
        entry10.setRating(10);
        entry10.setNotes("Best RPG ever.");
        entry10.setCreatedAt(java.time.Instant.parse("2017-07-01T10:00:00Z"));
        entry10.setUpdatedAt(java.time.Instant.parse("2018-12-01T10:00:00Z"));
        mediaTestData.add(entry10);

        UserLibraryEntry entry11 = new UserLibraryEntry();
        entry11.setMediaType("anime");
        entry11.setExternalId("an3");
        entry11.setTitle("Demon Slayer");
        entry11.setImageUrl("https://cdn.myanimelist.net/images/anime/1286/99889.jpg");
        entry11.setSourceUrl("https://anilist.co/anime/101922");
        entry11.setAuthor("Koyoharu Gotouge");
        entry11.setStatus(LibraryEntryStatus.IN_PROGRESS);
        java.util.Map<String, Object> meta11 = new java.util.HashMap<>();
        meta11.put("episodesWatched", 40);
        entry11.setMeta(meta11);
        entry11.setRating(8);
        entry11.setNotes("Tolle Animationen.");
        entry11.setCreatedAt(java.time.Instant.parse("2023-04-01T10:00:00Z"));
        entry11.setUpdatedAt(java.time.Instant.parse("2024-01-10T10:00:00Z"));
        mediaTestData.add(entry11);

        UserLibraryEntry entry12 = new UserLibraryEntry();
        entry12.setMediaType("manga");
        entry12.setExternalId("mn3");
        entry12.setTitle("Naruto");
        entry12.setImageUrl("https://cdn.myanimelist.net/images/manga/3/117681.jpg");
        entry12.setSourceUrl("https://myanimelist.net/manga/11/Naruto");
        entry12.setAuthor("Masashi Kishimoto");
        entry12.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta12 = new java.util.HashMap<>();
        meta12.put("chaptersRead", 700);
        entry12.setMeta(meta12);
        entry12.setRating(8);
        entry12.setNotes("Lange, aber lohnenswert.");
        entry12.setCreatedAt(java.time.Instant.parse("2015-05-01T12:00:00Z"));
        entry12.setUpdatedAt(java.time.Instant.parse("2016-01-15T09:00:00Z"));
        mediaTestData.add(entry12);

        UserLibraryEntry entry13 = new UserLibraryEntry();
        entry13.setMediaType("movie");
        entry13.setExternalId("mv3");
        entry13.setTitle("Interstellar");
        entry13.setImageUrl("https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg");
        entry13.setSourceUrl("https://www.imdb.com/title/tt0816692/");
        entry13.setAuthor("Christopher Nolan");
        entry13.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta13 = new java.util.HashMap<>();
        meta13.put("timesWatched", 2);
        entry13.setMeta(meta13);
        entry13.setRating(9);
        entry13.setNotes("Visually stunning.");
        entry13.setCreatedAt(java.time.Instant.parse("2016-11-20T18:30:00Z"));
        entry13.setUpdatedAt(java.time.Instant.parse("2017-12-01T20:00:00Z"));
        mediaTestData.add(entry13);

        UserLibraryEntry entry14 = new UserLibraryEntry();
        entry14.setMediaType("book");
        entry14.setExternalId("bk3");
        entry14.setTitle("To Kill a Mockingbird");
        entry14.setImageUrl("https://covers.openlibrary.org/b/id/8228691-L.jpg");
        entry14.setSourceUrl("https://openlibrary.org/works/OL82563W/To_Kill_a_Mockingbird");
        entry14.setAuthor("Harper Lee");
        entry14.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta14 = new java.util.HashMap<>();
        meta14.put("pagesRead", 281);
        entry14.setMeta(meta14);
        entry14.setRating(9);
        entry14.setNotes("Wichtige Botschaft.");
        entry14.setCreatedAt(java.time.Instant.parse("2014-03-10T14:00:00Z"));
        entry14.setUpdatedAt(java.time.Instant.parse("2014-03-20T14:00:00Z"));
        mediaTestData.add(entry14);

        UserLibraryEntry entry15 = new UserLibraryEntry();
        entry15.setMediaType("game");
        entry15.setExternalId("gm3");
        entry15.setTitle("Minecraft");
        entry15.setImageUrl("https://files.ekmcdn.com/6d7106/images/minecraft-poster-2464-p.jpg?w=472&h=9999&v=c90d4a1e-c975-4bb8-ab2f-1565591c9362");
        entry15.setSourceUrl("https://www.minecraft.net/");
        entry15.setAuthor("Mojang");
        entry15.setStatus(LibraryEntryStatus.IN_PROGRESS);
        java.util.Map<String, Object> meta15 = new java.util.HashMap<>();
        meta15.put("hoursPlayed", 500);
        entry15.setMeta(meta15);
        entry15.setRating(9);
        entry15.setNotes("Unendliche Möglichkeiten.");
        entry15.setCreatedAt(java.time.Instant.parse("2013-07-01T10:00:00Z"));
        entry15.setUpdatedAt(java.time.Instant.parse("2024-01-01T10:00:00Z"));
        mediaTestData.add(entry15);

        UserLibraryEntry entry16 = new UserLibraryEntry();
        entry16.setMediaType("anime");
        entry16.setExternalId("an4");
        entry16.setTitle("Jujutsu Kaisen");
        entry16.setImageUrl("https://cdn.myanimelist.net/images/anime/1171/109222.jpg");
        entry16.setSourceUrl("https://anilist.co/anime/40748");
        entry16.setAuthor("Gege Akutami");
        entry16.setStatus(LibraryEntryStatus.IN_PROGRESS);
        java.util.Map<String, Object> meta16 = new java.util.HashMap<>();
        meta16.put("episodesWatched", 36);
        entry16.setMeta(meta16);
        entry16.setRating(8);
        entry16.setNotes("Actionreich und spannend.");
        entry16.setCreatedAt(java.time.Instant.parse("2023-10-01T10:00:00Z"));
        entry16.setUpdatedAt(java.time.Instant.parse("2024-01-10T10:00:00Z"));
        mediaTestData.add(entry16);

        UserLibraryEntry entry17 = new UserLibraryEntry();
        entry17.setMediaType("manga");
        entry17.setExternalId("mn4");
        entry17.setTitle("Berserk");
        entry17.setImageUrl("https://cdn.myanimelist.net/images/manga/1/157897.jpg");
        entry17.setSourceUrl("https://myanimelist.net/manga/2/Berserk");
        entry17.setAuthor("Kentaro Miura");
        entry17.setStatus(LibraryEntryStatus.IN_PROGRESS);
        java.util.Map<String, Object> meta17 = new java.util.HashMap<>();
        meta17.put("chaptersRead", 370);
        entry17.setMeta(meta17);
        entry17.setRating(10);
        entry17.setNotes("Düster und episch.");
        entry17.setCreatedAt(java.time.Instant.parse("2012-05-01T12:00:00Z"));
        entry17.setUpdatedAt(java.time.Instant.parse("2024-01-15T09:00:00Z"));
        mediaTestData.add(entry17);

        UserLibraryEntry entry18 = new UserLibraryEntry();
        entry18.setMediaType("movie");
        entry18.setExternalId("mv4");
        entry18.setTitle("Spirited Away");
        entry18.setImageUrl("https://image.tmdb.org/t/p/original/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg");
        entry18.setSourceUrl("https://www.imdb.com/title/tt0245429/");
        entry18.setAuthor("Hayao Miyazaki");
        entry18.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta18 = new java.util.HashMap<>();
        meta18.put("timesWatched", 4);
        entry18.setMeta(meta18);
        entry18.setRating(10);
        entry18.setNotes("Zauberhaft.");
        entry18.setCreatedAt(java.time.Instant.parse("2010-11-20T18:30:00Z"));
        entry18.setUpdatedAt(java.time.Instant.parse("2011-12-01T20:00:00Z"));
        mediaTestData.add(entry18);

        UserLibraryEntry entry19 = new UserLibraryEntry();
        entry19.setMediaType("book");
        entry19.setExternalId("bk4");
        entry19.setTitle("The Catcher in the Rye");
        entry19.setImageUrl("https://covers.openlibrary.org/b/id/8231856-L.jpg");
        entry19.setSourceUrl("https://openlibrary.org/works/OL45804W/The_Catcher_in_the_Rye");
        entry19.setAuthor("J.D. Salinger");
        entry19.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta19 = new java.util.HashMap<>();
        meta19.put("pagesRead", 277);
        entry19.setMeta(meta19);
        entry19.setRating(7);
        entry19.setNotes("Interessant, aber speziell.");
        entry19.setCreatedAt(java.time.Instant.parse("2009-03-10T14:00:00Z"));
        entry19.setUpdatedAt(java.time.Instant.parse("2009-03-20T14:00:00Z"));
        mediaTestData.add(entry19);

        UserLibraryEntry entry20 = new UserLibraryEntry();
        entry20.setMediaType("game");
        entry20.setExternalId("gm4");
        entry20.setTitle("Portal 2");
        entry20.setImageUrl("https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg");
        entry20.setSourceUrl("https://www.thinkwithportals.com/");
        entry20.setAuthor("Valve");
        entry20.setStatus(LibraryEntryStatus.COMPLETED);
        java.util.Map<String, Object> meta20 = new java.util.HashMap<>();
        meta20.put("hoursPlayed", 30);
        entry20.setMeta(meta20);
        entry20.setRating(9);
        entry20.setNotes("Rätselspaß pur.");
        entry20.setCreatedAt(java.time.Instant.parse("2012-07-01T10:00:00Z"));
        entry20.setUpdatedAt(java.time.Instant.parse("2013-12-01T10:00:00Z"));
        mediaTestData.add(entry20);


        

        return mediaTestData;
    }
}
